################################################################################
# Copyright (c) 2019 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v2.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v20.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
################################################################################


apiVersion: v1
kind: Service
metadata:
  name: codewind-WORKSPACE_ID_PLACEHOLDER
  labels:
    app: codewind-pfe
    pfeWorkspace: WORKSPACE_ID_PLACEHOLDER
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: OWNER_REFERENCE_NAME_PLACEHOLDER
      uid: OWNER_REFERENCE_UID_PLACEHOLDER
spec:
  ports:
    - port: 9191
      name: portal-http
  selector:
    pfeWorkspace: WORKSPACE_ID_PLACEHOLDER

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: codewind-WORKSPACE_ID_PLACEHOLDER
  labels:
    app: codewind-pfe
    workspace: WORKSPACE_ID_PLACEHOLDER
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: OWNER_REFERENCE_NAME_PLACEHOLDER
      uid: OWNER_REFERENCE_UID_PLACEHOLDER
spec:
  selector:
    matchLabels:
      app: codewind-pfe
  replicas: 1
  template:
    metadata:
      labels:
        app: codewind-pfe
        pfeWorkspace: WORKSPACE_ID_PLACEHOLDER
      annotations:
        productName: "codewind"
        productID: "codewind"
        productVersion: "0.2.0"

    spec:
      serviceAccountName: SERVICE_ACCOUNT_PLACEHOLDER
      affinity:        
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
      volumes:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: PVC_NAME_PLACEHOLDER
      - name: buildah-volume
      - name: registry-secret
        secret:
          defaultMode: 0777
          secretName: REGISTRY_SECRET_PLACEHOLDER
          optional: true
      containers:
      - name: codewind-pfe
        image: sys-mcs-docker-local.artifactory.swg-devops.com/codewind-pfe-amd64:latest
        imagePullPolicy: "Always"
        securityContext:
          privileged: true
        volumeMounts:
        - name: shared-workspace
          mountPath: /codewind-workspace
          subPath: "WORKSPACE_ID_PLACEHOLDER/projects"
        - name: buildah-volume
          mountPath: "/var/lib/containers"
        - name: registry-secret
          mountPath: "/tmp/secret"
        env:
          - name: IN_K8
            value: "true"
          - name: PORTAL_HTTPS
            value: "true"
          - name: KUBE_NAMESPACE
            value: "KUBE_NAMESPACE_PLACEHOLDER"
          - name: TILLER_NAMESPACE
            value: "KUBE_NAMESPACE_PLACEHOLDER"
          - name: CHE_WORKSPACE_ID
            value: "WORKSPACE_ID_PLACEHOLDER"
          - name: PVC_NAME
            value: PVC_NAME_PLACEHOLDER
          - name: SERVICE_NAME
            value: codewind-WORKSPACE_ID_PLACEHOLDER
          - name: DOCKER_REGISTRY_SECRET
            value: "REGISTRY_SECRET_PLACEHOLDER"
          - name: SERVICE_ACCOUNT_NAME
            value: SERVICE_ACCOUNT_PLACEHOLDER
          - name: MICROCLIMATE_RELEASE_NAME
            value: RELEASE-NAME
          - name: HOST_WORKSPACE_DIRECTORY
            value: /projects
          - name: CONTAINER_WORKSPACE_DIRECTORY
            value: /codewind-workspace
          - name: EXTRA_GIT_OPTION
            value: ""
          - name: OWNER_REF_NAME
            value: OWNER_REFERENCE_NAME_PLACEHOLDER
          - name: OWNER_REF_UID
            value: OWNER_REFERENCE_UID_PLACEHOLDER
        ports:
        - containerPort: 9191
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: 500m
